### ISSUE TITLE
Office Add-ins July 2022 blog won't publish

### ISSUE THREAD

**Issue by davidchesnut** [pnp/blog#521]
#### Article issue

The article at https://github.com/pnp/blog/tree/main/content/office-add-ins-community-call/2022-07-13 won't publish. Can you help us get it live? Thanks!

**Comment by LuiseFreese** [comment]
Hi @davidchesnut - 

The blog post published, but as the **date** property in the front matter is at `2022-07-22T08:01:00-05:00` and we sort the articles publishing date you will need to either scroll through the pages (and right now you can find the post on page 4 or you can filter by category --> https://pnp.github.io/blog/categories/office-add-in-developer-community-call/. 

Do you want to change the publishing date to two days ago when it was actually published? The PR really had a long processing time due to all those wording/formatting changes. 

Best practice from my experience is to get those articles out asap after the community call and PR/improve if someone sees issues/typos. 

Let me know if I can help.

**Comment by davidchesnut** [comment]
Ah, got it. Yeah I thought it would be on the first or second page. Good to know. No worries on the date, we'll work to get them out quicker :-)

Thanks!
